### ISSUE TITLE
Make project plan

### ISSUE THREAD

**Issue by Nadran20** [Nadran20/project_language_compilation_S5#1]
- [x]  Make project plan

- [x] Separate the different tasks of the project

- [x] Assign tasks

- [x] Finish the project :)
